language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_1adc5a02a324_key -iv $encrypted_1adc5a02a324_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

script: true

addons:
  ssh_known_hosts: $host_ip

after_success:
- scp -o stricthostkeychecking=no -r dist/* $host_user@$host_ip:$user_file_addr